### ISSUE TITLE
UTC?

### ISSUE THREAD

**Issue by ahmetanildindar** [osmanyilmazco/earthquakes#1]
Merhabalar,
Güzel bir kod olmuş, ellerinize sağlık. 

Bir sorum olacak, KOERI sitesinden UTC zamanı olarak zaman belirtmek istersek öneriniz olur? 

Yani gelen veriyi lokalde mi UTC'ye çevirmeli? Yoksa KOERI'de yer alan http://www.koeri.boun.edu.tr/scripts/lasteq.asp adresindeki veriyi mi kullanmalı?

++Ahmet Anıl Dindar

**Comment by osmanyz** [comment]
Merhaba, Teşekkür ederim. Tavsiyem, KOERI'de yer alan veriyi kullanmanız olacaktır. Eğer ihtiyacınızı karşılamıyorsa; lokal'de çevirirsiniz.

**Comment by ahmetanildindar** [comment]
Merhabalar,
Maalesef KOERI'nin UTC verilerini sizin programınızla almak mümkün olmadı.

Ben de bu yüzden python pytz modülünü kullanarak lokalde zamanları UTC'ye
çevirdim.

**Comment by osmanyz** [comment]
O zaman kolay gelsin, iyi çalışmalar dilerim.
